In [1]:
import pandas as pd 
import numpy as np

In [3]:
#load main data set 
df = pd.read_csv("D:/nassau_profitability_project/data/raw/nassau_candy.csv")

#load mapping file 
product_factory = pd.read_csv("D:/nassau_profitability_project/data/mapping/product_factory_mapping.csv")
factory_coords = pd.read_csv("D:/nassau_profitability_project/data/mapping/factory_coordinates.csv")

In [4]:
# checking shape 
print("main data shape ", df.shape )
print("product factory shape ",product_factory.shape)
print ("factory coordinate shape ", factory_coords.shape)

main data shape  (10194, 18)
product factory shape  (15, 3)
factory coordinate shape  (5, 3)

In [5]:
#preview data
df.head ()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [6]:
product_factory.head()

    division                       product_name          factory
0  Chocolate  Wonka Bar - Nutty Crunch Surprise    Lot's O' Nuts
1  Chocolate          Wonka Bar - Fudge Mallows    Lot's O' Nuts
2  Chocolate     Wonka Bar -Scrumdiddlyumptious    Lot's O' Nuts
3  Chocolate         Wonka Bar - Milk Chocolate  Wicked Choccy's
4  Chocolate  Wonka Bar - Triple Dazzle Caramel  Wicked Choccy's

In [7]:
factory_coords.head()

             factory   latitude   longitude
0      Lot's O' Nuts  32.881893 -111.768036
1    Wicked Choccy's  32.076176  -81.088371
2        Sugar Shack  48.119140  -96.181150
3     Secret Factory  41.446333  -90.565487
4  The Other Factory  35.117500  -89.971107

In [8]:
#standarlized column names 
df.columns = (df.columns
.str.strip()
.str.lower()
.str.replace("/","_", regex = False )
.str.replace (" ", "_", regex = False )
.str.replace ("-","_", regex = False))

product_factory.columns = (product_factory.columns.
                           str.strip()
                           )
factory_coords.columns = (factory_coords.columns .str . lower ())

In [9]:
print (df.columns.to_list())

['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'country_region', 'city', 'state_province', 'postal_code', 'division', 'region', 'product_id', 'product_name', 'sales', 'units', 'gross_profit', 'cost']

In [10]:
print(product_factory.columns. to_list())
print(factory_coords.columns.to_list())

['division', 'product_name', 'factory']
['factory', 'latitude', 'longitude']

In [11]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   row_id          10194 non-null  int64
 1   order_id        10194 non-null  str
 2   order_date      10194 non-null  str
 3   ship_date       10194 non-null  str
 4   ship_mode       10194 non-null  str
 5   customer_id     10194 non-null  int64
 6   country_region  10194 non-null  str
 7   city            10194 non-null  str
 8   state_province  10194 non-null  str
 9   postal_code     10194 non-null  str
 10  division        10194 non-null  str
 11  region          10194 non-null  str
 12  product_id      10194 non-null  str
 13  product_name    10194 non-null  str
 14  sales           10194 non-null  float64
 15  units           10194 non-null  int64
 16  gross_profit    10194 non-null  float64
 17  cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 1.4 MB
None

In [12]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
row_id,10194.0,NaN,NaN,NaN,5097.5,2942.898656,1.0,2549.25,5097.5,7645.75,10194.0
order_id,10194,8549,US-2021-155502-CHO-MIL-31000,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_date,10194,717,02-09-2025,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ship_date,10194,1338,07-06-2028,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ship_mode,10194,4,Standard Class,6120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,10194.0,NaN,NaN,NaN,134468.961154,20231.483007,100006.0,117212.0,133550.0,152051.0,192314.0
country_region,10194,2,United States,9994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
city,10194,542,New York City,915,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state_province,10194,59,California,2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
postal_code,10194,654,10035,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN
division,10194,3,Chocolate,9844,NaN,NaN,NaN,NaN,NaN,NaN,NaN
region,10194,4,Pacific,3253,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_id,10194,15,CHO-MIL-31000,2137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name,10194,15,Wonka Bar - Milk Chocolate,2137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sales,10194.0,NaN,NaN,NaN,13.908537,11.34102,1.25,7.2,10.8,18.0,260.0
units,10194.0,NaN,NaN,NaN,3.791838,2.228317,1.0,2.0,3.0,5.0,14.0
gross_profit,10194.0,NaN,NaN,NaN,9.166451,6.64374,0.25,4.9,7.47,12.25,130.0
cost,10194.0,NaN,NaN,NaN,4.742087,5.061647,0.6,2.4,3.6,5.7,130.0

In [13]:
factory_coords.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
factory,5,5,Lot's O' Nuts,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,5.0,NaN,NaN,NaN,37.928208,6.779453,32.076176,32.881893,35.1175,41.446333,48.11914
longitude,5.0,NaN,NaN,NaN,-93.91483,11.348593,-111.768036,-96.18115,-90.565487,-89.971107,-81.088371

In [14]:
product_factory.describe(include="all").T

             count unique                                top freq
division        15      3                              Sugar    6
product_name    15     15  Wonka Bar - Nutty Crunch Surprise    1
factory         15      5                        Sugar Shack    5

In [15]:
#checking null values and sort them 
df.isnull().sum().sort_values(ascending=False)

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
country_region    0
city              0
state_province    0
postal_code       0
division          0
region            0
product_id        0
product_name      0
sales             0
units             0
gross_profit      0
cost              0
dtype: int64

In [16]:
#check duplicates 
print("duplicates rows : ", df.duplicated().sum())

duplicates rows :  0

In [17]:
text_columns = df.columns.astype(str)
print(text_columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country_region', 'city', 'state_province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost'],
      dtype='str')

In [18]:
text_cols = ['order_id','product_id','ship_mode','customer_id','country_region','city','state-province','divison','product_name',]

for col in text_cols:
    if col in df.columns:
        df[col] = df[col].astype(str).str.strip()

In [20]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country_region', 'city', 'state_province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost'],
      dtype='str')

In [19]:
df['order_date'].head(10)

0    03-01-2024
1    04-01-2024
2    04-01-2024
3    04-01-2024
4    05-01-2024
5    06-01-2024
6    06-01-2024
7    06-01-2024
8    06-01-2024
9    06-01-2024
Name: order_date, dtype: str

In [20]:
##convert date format
df["order_date"] = df["order_date"].astype(str).str.strip()

df["order_date"] = pd.to_datetime(
    df["order_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [21]:
df['ship_date'].head(10)

0    30-06-2026
1    01-07-2026
2    01-07-2026
3    01-07-2026
4    05-07-2026
5    03-07-2026
6    03-07-2026
7    30-06-2026
8    03-07-2026
9    03-07-2026
Name: ship_date, dtype: str

In [22]:
#convert date format 
df["ship_date"] = df["ship_date"].astype(str).str.strip()

df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    format="%d-%m-%Y",
    errors="coerce"
)

In [23]:
df.isnull().sum()

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
country_region    0
city              0
state_province    0
postal_code       0
division          0
region            0
product_id        0
product_name      0
sales             0
units             0
gross_profit      0
cost              0
dtype: int64

In [24]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   row_id          10194 non-null  int64
 1   order_id        10194 non-null  str
 2   order_date      10194 non-null  datetime64[us]
 3   ship_date       10194 non-null  datetime64[us]
 4   ship_mode       10194 non-null  str
 5   customer_id     10194 non-null  str
 6   country_region  10194 non-null  str
 7   city            10194 non-null  str
 8   state_province  10194 non-null  str
 9   postal_code     10194 non-null  str
 10  division        10194 non-null  str
 11  region          10194 non-null  str
 12  product_id      10194 non-null  str
 13  product_name    10194 non-null  str
 14  sales           10194 non-null  float64
 15  units           10194 non-null  int64
 16  gross_profit    10194 non-null  float64
 17  cost            10194 non-null  float64
dtypes: datetime64[us](2), float64(3), int64(2), str(11)
memory usage: 1.4 MB
None

In [25]:
#check null value of order date and ship date 
print("Null order_date:", df["order_date"].isna().sum())
print("Null ship_date:", df["ship_date"].isna().sum())

Null order_date: 0
Null ship_date: 0

In [27]:
#convert numeric columns
key_cols = ["sales", "units", "gross_profit", "cost", "division", "product_name"]
df[key_cols].isnull().sum()

sales           0
units           0
gross_profit    0
cost            0
division        0
product_name    0
dtype: int64

-remove rows where sales is missing or <= 0
-remove rows where cost is missing or < 0
-if gross_profit is missing and both sales/cost exist, calculate it
-if units is missing or <= 0, remove row for now because profit per unit will be needed
-remove rows where product_name or division is missing

In [28]:
# Fill gross_profit if missing and sales/cost available
"""Agar gross_profit missing hai (NaN hai) aur sales aur cost available hai,
to gross_profit = sales - cost kar do,
warna jo pehle value hai wahi rehne do."""

df["gross_profit"] = np.where(
    df["gross_profit"].isna() & df["sales"].notna() & df["cost"].notna(),
    df["sales"] - df["cost"],
    df["gross_profit"]
)

# Remove rows with critical missing text fields if there is any missing value in the subset division and product name 
df = df.dropna(subset=["division", "product_name"])

# Remove invalid business rows if sales , cost , units grater than 0 keep otherwise delete 
df = df[df["sales"] > 0]
df = df[df["cost"] >= 0]
df = df[df["units"] > 0]
df = df[df["gross_profit"].notna()]

In [29]:
#remove duplicates 
print("Duplicate rows before removal:", df.duplicated().sum())
#how much gross profit filled by gross profit = sales - cost
print ("filling filled :", df["gross_profit"].isna().sum())

Duplicate rows before removal: 0
filling filled : 0

gross_profit ≈ sales - cost

In [62]:
#we check profit validation
df["calculated_profit"] = df["sales"] - df["cost"]
df["profit_diff"] = df["gross_profit"] - df["calculated_profit"]
df["profit_diff_abs"] = df["profit_diff"].abs()
df["profit_diff_abs"] = df["profit_diff_abs"].round(2)

In [31]:
df[["gross_profit", "calculated_profit", "profit_diff"]].head().round(2)

   gross_profit  calculated_profit  profit_diff
0          4.22               4.22         -0.0
1          4.90               4.90          0.0
2          7.47               7.47         -0.0
3          7.50               7.50         -0.0
4          7.35               7.35          0.0

In [32]:
df["profit_diff_abs"].describe().round(2)

count    10194.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: profit_diff_abs, dtype: float64

In [33]:
tolerance = 0.01

invalid_profit_rows = df[df["profit_diff_abs"] > tolerance]
print("Rows with profit mismatch:", invalid_profit_rows.shape[0])

Rows with profit mismatch: 0

In [34]:
df["gross_profit"] = df["calculated_profit"]

In [37]:
df["profit_diff"] = df["gross_profit"] - (df["sales"] - df["cost"])
df["profit_diff"].abs().max()

np.float64(0.0)

In [36]:
print("Rows with negative gross profit:", (df["gross_profit"] < 0).sum())

Rows with negative gross profit: 0

In [39]:
invalid_ship_dates = df[df["ship_date"] < df["order_date"]]
print("Rows where ship_date < order_date:", invalid_ship_dates.shape[0])

Rows where ship_date < order_date: 0

Create shipping metric

In [40]:
df["shipping_days"] = (df["ship_date"] - df["order_date"]).dt.days

In [41]:
df["shipping_days"].describe()

count    10194.000000
mean      1320.841868
std        262.444892
min        904.000000
25%       1271.000000
50%       1274.000000
75%       1638.000000
max       1642.000000
Name: shipping_days, dtype: float64

In [42]:
print(product_factory.columns. to_list())
print(factory_coords.columns.to_list())

['division', 'product_name', 'factory']
['factory', 'latitude', 'longitude']

Merge product-factory mapping

In [42]:
product_factory["product_name"] = product_factory["product_name"].astype(str).str.strip()
product_factory["division"] = product_factory["division"].astype(str).str.strip()

factory_coords["factory"] = factory_coords["factory"].astype(str).str.strip()

df["product_name"] = df["product_name"].astype(str).str.strip()
df["division"] = df["division"].astype(str).str.strip()

In [43]:
df = df.merge(
    product_factory,
    on=["division", "product_name"],
    how="left"
)

In [45]:
print("Missing factory after merge:", df["factory"].isna().sum())

Missing factory after merge: 6

In [47]:
missing_factory_rows = df[df["factory"].isna()]
print(missing_factory_rows[["division", "product_name"]])

     division          product_name
191     Sugar  Fizzy Lifting Drinks
227     Sugar  Fizzy Lifting Drinks
2716    Sugar  Fizzy Lifting Drinks
6736    Sugar  Fizzy Lifting Drinks
6912    Sugar  Fizzy Lifting Drinks
7379    Sugar  Fizzy Lifting Drinks

In [48]:
product_factory[
    (product_factory["division"] == "Sugar") &
    (product_factory["product_name"] == "Fizzy Lifting Drinks")
]

Empty DataFrame
Columns: [division, product_name, factory]
Index: []

In [49]:
df["factory"] = df["factory"].fillna("Unknown")

Merge factory coordinates

In [50]:
df = df.merge(
    factory_coords,
    on="factory",
    how="left"
)

In [51]:
print("Missing latitude:", df["latitude"].isna().sum())
print("Missing longitude:", df["longitude"].isna().sum())

Missing latitude: 6
Missing longitude: 6

In [52]:
df["latitude"] = df["latitude"].fillna(0)
df["longitude"] = df["longitude"].fillna(0)

In [53]:
df.duplicated().sum()

np.int64(0)

create time features

In [54]:
df["year"] = df["order_date"].dt.year
df["month"] = df["order_date"].dt.month
df["month_name"] = df["order_date"].dt.month_name()
df["quarter"] = df["order_date"].dt.quarter
df["year_month"] = df["order_date"].dt.to_period("M").astype(str)

In [55]:
df[["order_date", "year", "month", "month_name", "quarter", "year_month"]].head()

  order_date  year  month month_name  quarter year_month
0 2024-01-03  2024      1    January        1    2024-01
1 2024-01-04  2024      1    January        1    2024-01
2 2024-01-04  2024      1    January        1    2024-01
3 2024-01-04  2024      1    January        1    2024-01
4 2024-01-05  2024      1    January        1    2024-01

In [56]:
print("Final shape:", df.shape)
print("\nNull values:\n", df.isnull().sum().sort_values(ascending=False).head(20))

Final shape: (10194, 30)

Null values:
 row_id               0
order_id             0
order_date           0
ship_date            0
ship_mode            0
customer_id          0
country_region       0
city                 0
state_province       0
postal_code          0
division             0
region               0
product_id           0
product_name         0
sales                0
units                0
gross_profit         0
cost                 0
calculated_profit    0
profit_diff          0
dtype: int64

In [57]:
df[["sales", "cost", "gross_profit", "units", "shipping_days"]].describe()

              sales          cost  gross_profit         units  shipping_days
count  10194.000000  10194.000000  10194.000000  10194.000000   10194.000000
mean      13.908537      4.742087      9.166451      3.791838    1320.841868
std       11.341020      5.061647      6.643740      2.228317     262.444892
min        1.250000      0.600000      0.250000      1.000000     904.000000
25%        7.200000      2.400000      4.900000      2.000000    1271.000000
50%       10.800000      3.600000      7.470000      3.000000    1274.000000
75%       18.000000      5.700000     12.250000      5.000000    1638.000000
max      260.000000    130.000000    130.000000     14.000000    1642.000000

In [60]:
df["division"].value_counts(dropna=False)

division
Chocolate    9844
Other         310
Sugar          40
Name: count, dtype: int64

In [63]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,country_region,city,state_province,postal_code,...,profit_diff_abs,shipping_days,factory,latitude,longitude,year,month,month_name,quarter,year_month
0,1,US-2021-103800-CHO-MIL-31000,2024-01-03,2026-06-30,Standard Class,103800,United States,Houston,Texas,77095,...,0.0,909,Wicked Choccy's,32.076176,-81.088371,2024,1,January,1,2024-01
1,2,US-2021-112326-CHO-TRI-54000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,0.0,909,Wicked Choccy's,32.076176,-81.088371,2024,1,January,1,2024-01
2,3,US-2021-112326-CHO-NUT-13000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,0.0,909,Lot's O' Nuts,32.881893,-111.768036,2024,1,January,1,2024-01
3,4,US-2021-112326-CHO-SCR-58000,2024-01-04,2026-07-01,Standard Class,112326,United States,Naperville,Illinois,60540,...,0.0,909,Lot's O' Nuts,32.881893,-111.768036,2024,1,January,1,2024-01
4,5,US-2021-141817-CHO-TRI-54000,2024-01-05,2026-07-05,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,...,0.0,912,Wicked Choccy's,32.076176,-81.088371,2024,1,January,1,2024-01

In [67]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'country_region', 'city', 'state_province',
       'postal_code', 'division', 'region', 'product_id', 'product_name',
       'sales', 'units', 'gross_profit', 'cost', 'calculated_profit',
       'profit_diff', 'profit_diff_abs', 'shipping_days', 'factory',
       'latitude', 'longitude', 'year', 'month', 'month_name', 'quarter',
       'year_month'],
      dtype='str')

In [66]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   row_id             10194 non-null  int64
 1   order_id           10194 non-null  str
 2   order_date         10194 non-null  datetime64[us]
 3   ship_date          10194 non-null  datetime64[us]
 4   ship_mode          10194 non-null  str
 5   customer_id        10194 non-null  str
 6   country_region     10194 non-null  str
 7   city               10194 non-null  str
 8   state_province     10194 non-null  str
 9   postal_code        10194 non-null  str
 10  division           10194 non-null  str
 11  region             10194 non-null  str
 12  product_id         10194 non-null  str
 13  product_name       10194 non-null  str
 14  sales              10194 non-null  float64
 15  units              10194 non-null  int64
 16  gross_profit       10194 non-null  float64
 17  cost               10194 non-null  float64
 18  calculated_profit  10194 non-null  float64
 19  profit_diff        10194 non-null  float64
 20  profit_diff_abs    10194 non-null  float64
 21  shipping_days      10194 non-null  int64
 22  factory            10194 non-null  str
 23  latitude           10194 non-null  float64
 24  longitude          10194 non-null  float64
 25  year               10194 non-null  int32
 26  month              10194 non-null  int32
 27  month_name         10194 non-null  str
 28  quarter            10194 non-null  int32
 29  year_month         10194 non-null  str
dtypes: datetime64[us](2), float64(8), int32(3), int64(3), str(14)
memory usage: 2.2 MB

In [68]:
df.to_csv("D:/nassau_profitability_project/data/processed/nassau_cleaned.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.